name: Publish
on:
  push:
    branch: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Configure npm
        run: |
          echo @atillasertkaya:registry=https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}